[profile.default]
src = "src"
out = "out"
via_ir = true
optimizer = true
optimizer_runs = 200
libs = ["lib", "openzeppelin-contracts,forge-std"]
chain_id = 84532
remappings = [
	"forge-std/=lib/forge-std/src/",
	"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
base = "https://sepolia.base.org"

